class url():
    HOME = 'http://narutogame.com.br/'
    NINJA_SELECT = 'http://narutogame.com.br/index.php?secao=personagem_selecionar'
    TRAINING_ATTRIBUTES = 'http://narutogame.com.br/index.php?secao=academia_treinamento'
    NINJA_STATUS = 'http://narutogame.com.br/index.php?secao=personagem_status'
    TASK = 'http://narutogame.com.br/index.php?secao=licoes'
    MISSION_STATUS = 'http://narutogame.com.br/index.php?secao=missoes_espera'
    DOJO_FIGHT = 'http://narutogame.com.br/index.php?secao=dojo_batalha_lutador'
    HISTORY_MODE = 'http://narutogame.com.br/index.php?secao=historia'

class id_():
    FORMULARIO = 'formulario'
    EMAIL = 'email'
    PASSWORD = 'senha'
    RIGHT = 'direita'
    LEFT = 'esquerda'
    NINJA_NAME = 'cnNinjaP'
    NINJA_LEVEL = 'cnLevelP'
    NINJA_RYOUS = 'cnRyouP'
    QUANTITY = 'qtd'
    PAGE_BODY = 'cnBase'
    STATUS_ICONS = 'icones'
    HEART_ICON = 'cnEHPt'
    CHAKRA_ICON = 'cnESPt'
    STAMINA_ICON = 'cnESTAt'
    SKILLS_CONTAINER = 'actionbar-container'
    SKILL_LIST = 'attack-list'
    PLAYER_HEART = 'cnPHP'
    PLAYER_CHAKRA = 'cnPSP'
    PLAYER_STAMINA = 'cnPSTA'
    ENEMY_HEART = 'cnEHP'
    ENEMY_CHAKRA = 'cnESP'
    ENEMY_STAMINA = 'cnESTA'
    BATTLE_MESSAGE = 'cnFinal'
    BUTTONS_TAB = 'modoh-tabs'
    HM_BATTLE_PAGE1 = 'historia-base-210'
    HM_BATTLE_PAGE2 = 'historia-base-211'
    HM_BATTLE_PAGE3 = 'historia-base-240'
    HM_BATTLE_PAGE4 = 'historia-base-362'


class skill():
    HAND_DEFEND = 'atki-6'
    ACROBACY = 'atki-7'
    PUNCH = 'atki-4'
    KICK = 'atki-5'
    #Tai skills - ID
    DYNAMIC_KICK = 'atki-709'

class css():
    NINJA_SELECT_IMAGE = '.d-img-p.char-page.char-page-1'
    NAME = '.name'
    POP_UP = '.ui-dialog'
    BUTTON = '.button'
    DISABLED = '.ui-state-disabled'
    CLOSE = '.ui-dialog-titlebar-close'
    BATTLE_LEFT = '.a-esquerda-batalha'
    BATTLE_RIGHT = '.b-direita-batalha'
    NAME_BATTLE = '.player-name'
    BATTLE_OPTIONS = '.pvp-atk-filter-selected'
    TEXT_LINK = '.linkTopo'
    COMPLETE_HISTORY = '.historia-titulo-completo'
    HISTORY = '.historia-saga'
    EXPAND_BUTTON = '.b-historia-saga'
    HISTORY_EXPANDED = '.shown'
