#URLs
HOME_URL = 'http://narutogame.com.br/'
NINJA_SELECT_URL = 'http://narutogame.com.br/index.php?secao=personagem_selecionar'
TRAINING_ATTRIBUTES_URL = 'http://narutogame.com.br/index.php?secao=academia_treinamento'
NINJA_STATUS_URL = 'http://narutogame.com.br/index.php?secao=personagem_status'
TASK_URL = 'http://narutogame.com.br/index.php?secao=licoes'
MISSION_STATUS_URL = 'http://narutogame.com.br/index.php?secao=missoes_espera'
DOJO_FIGHT_URL = 'http://narutogame.com.br/index.php?secao=dojo_batalha_lutador'

#IDs
FORMULARIO_ID = 'formulario'
EMAIL_ID = 'email'
PASSWORD_ID = 'senha'
RIGHT_ID = 'direita'
LEFT_ID = 'esquerda'
NINJA_NAME_ID = 'cnNinjaP'
NINJA_LEVEL_ID = 'cnLevelP'
NINJA_RYOUS_ID = 'cnRyouP'
QUANTITY_ID = 'qtd'
PAGE_BODY_ID = 'cnBase'
STATUS_ICONS_ID = 'icones'
HEART_ICON_ID = 'cnPHPt'
CHAKRA_ICON_ID = 'cnPSPt'
STAMINA_ICON_ID = 'cnPSTAt'
SKILLS_CONTAINER_ID = 'actionbar-container'
SKILL_LIST_ID = 'attack-list'
HEART_BATTLE_ID = 'cnPHP'
CHAKRA_BATTLE_ID = 'cnPSP'
STAMINA_BATTLE_ID = 'cnPSTA'
BATTLE_MESSAGE_ID = 'cnFinal'

#Basic Skills - ID
HAND_DEFEND = 'atki-6'
ACROBACY = 'atki-7'
PUNCH = 'atki-4'
KICK = 'atki-5'
#Tai skills - ID
DYNAMIC_KICK = 'atki-709'


#CSS
NINJA_SELECT_IMAGE_CSS = '.d-img-p.char-page.char-page-1'
NAME_CSS = '.name'
POP_UP_CSS = '.ui-dialog'
BUTTON_CSS = '.button'
DISABLED_CSS = '.ui-state-disabled'
CLOSE_CSS = '.ui-dialog-titlebar-close'
BATTLE_LEFT_CSS = '.a-esquerda-batalha'
BATTLE_RIGHT_CSS = '.b-direita-batalha'
NAME_BATTLE_CSS = '.player-name'
BATTLE_OPTIONS_CSS = '.pvp-atk-filter-selected'
TEXT_LINK_CSS = '.linkTopo'
